package com.example.polydeadlines.ui.theme

import androidx.compose.ui.graphics.Color



val md_theme_light_primary = Color(0xFF27BB3D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA7D3AE)
val md_theme_light_onPrimaryContainer = Color(0xFF152900)
val md_theme_light_secondary = Color(0xFF566F40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCFFBBC)
val md_theme_light_onSecondaryContainer = Color(0xFF132704)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFBFFD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF00411F)
val md_theme_light_background = Color(0xFFD5D4D5)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1F16)
val md_theme_light_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_onSurfaceVariant = Color(0xFF474F39)
val md_theme_light_outline = Color(0xFF7A8167)
val md_theme_light_inverseOnSurface = Color(0xFFF6F9E7)
val md_theme_light_inverseSurface = Color(0xFF30342A)
val md_theme_light_inversePrimary = Color(0xFFE5FF51)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF458200)
val md_theme_light_outlineVariant = Color(0xFFD0D3B4)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_dark_primary = Color(0xFF27BB3D)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF1A6300)
val md_theme_dark_onPrimaryContainer = Color(0xFFC7FFB3)
val md_theme_dark_secondary = Color(0xFFAEDDA1)
val md_theme_dark_onSecondary = Color(0xFF223E16)
val md_theme_dark_secondaryContainer = Color(0xFF32562A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2FBBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val md_theme_dark_error = Color(0xFFFFFBAB)
val md_theme_dark_errorContainer = Color(0xFF004293)
val md_theme_dark_onError = Color(0xFF002769)
val md_theme_dark_onErrorContainer = Color(0xFFF7FFD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF424140)
val md_theme_dark_onSurfaceVariant = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFF849C80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFE5EAD9)
val md_theme_dark_inversePrimary = Color(0xFF3D8200)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF6F8F5)
val md_theme_dark_outlineVariant = Color(0xFF404F39)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF238200)
